
export const seedProductData = [
  {
    name: 'Cow Milk',
    description: 'Fresh and pure cow milk, sourced from local healthy cows. Perfect for daily consumption.',
    pricePerUnit: 55,
    units: ['litre', 'ml'],
    defaultUnit: 'litre',
    image: 'https://media.istockphoto.com/id/535489242/photo/pouring-milk-in-the-glass-on-the-background-of-nature.jpg?s=612x612&w=0&k=20&c=bqBubtMFs_kv9z0OZVLunl3NFTb_XAVKiw8v1hO1T80=',
    category: 'milk',
  },
  {
    name: 'Buffalo Milk',
    description: 'Rich and creamy buffalo milk, high in fat content, ideal for making traditional sweets and thick curd.',
    pricePerUnit: 70,
    units: ['litre', 'ml'],
    defaultUnit: 'litre',
    image: 'https://img.freepik.com/free-photo/pitcher-with-some-milk_93675-128649.jpg?semt=ais_hybrid&w=740&q=80',
    category: 'milk',
  },
  {
    name: 'A2 Desi Ghee',
    description: 'Pure Desi Ghee made from A2 cow milk using the traditional bilona method. Rich aroma and granular texture.',
    pricePerUnit: 900,
    units: ['kg', 'g'],
    defaultUnit: 'kg',
    image: 'https://t3.ftcdn.net/jpg/14/38/02/02/360_F_1438020262_6XBwH74PjQ6QLaDUiTZ90dSMfyIjoGUK.jpg',
    category: 'ghee',
  },
  {
    name: 'Fresh Paneer',
    description: 'Soft and fresh paneer (cottage cheese), made from pure milk. Perfect for curries and snacks.',
    pricePerUnit: 350,
    units: ['kg', 'g'],
    defaultUnit: 'kg',
    image: 'https://img.freepik.com/premium-photo/paneer-isolated-white-background_759447-1790.jpg',
    category: 'paneer',
  },
  {
    name: 'Thick Curd (Dahi)',
    description: 'Creamy and thick curd, naturally set to perfection. Good for digestion and a great accompaniment to any meal.',
    pricePerUnit: 70,
    units: ['kg', 'g'],
    defaultUnit: 'kg',
    image: 'https://tiimg.tistatic.com/fp/1/008/186/fresh-sweet-white-curd-658.jpg',
    category: 'curd',
  },
  {
    name: 'Khoya (Mawa)',
    description: 'Authentic Khoya, also known as Mawa, is a dried evaporated milk solid used in a variety of Indian sweets.',
    pricePerUnit: 400,
    units: ['kg', 'g'],
    defaultUnit: 'kg',
    image: 'https://img.freepik.com/premium-photo/khoa-khua-khoya-mawa-is-dairy-food-originating-from-indian-subcontinent-widely-used-cuisines-indian-subcontinent_466689-69599.jpg',
    category: 'khoya',
  },
  {
    name: 'Fresh Chhena',
    description: 'Soft and fresh Chhena, the base for many famous Bengali sweets like Rasgulla and Sandesh.',
    pricePerUnit: 300,
    units: ['kg', 'g'],
    defaultUnit: 'kg',
    image: 'https://www.shutterstock.com/image-photo/indian-rasgulla-dry-rosogulla-dessertsweet-600nw-1849158193.jpg',
    category: 'chhena',
  },
];
